FROM python:3.12-slim

ENV PYTHONUNBUFFERED=TRUE

RUN pip install poetry==1.6.1

RUN poetry config virtualenvs.create false

WORKDIR /code

COPY ./pyproject.toml ./README.md ./poetry.lock* ./

COPY ./package[s] ./packages

RUN poetry install  --no-interaction --no-ansi --no-root

COPY ./app ./app

RUN poetry install --no-interaction --no-ansi

EXPOSE 8080

CMD ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8080"]

# deploy
# gcloud run deploy kinmi-ai --source . --port 8080 --allow-unauthenticated --region us-west1 --project letting-415104